### ISSUE TITLE
Group names without role split delimiter crashes on checking permissions

### ISSUE THREAD

**Issue by websi96** [TU-Wien-dataLAB/Grader-Service#10]
**Describe the bug**

We have multiple groups of which not all reflect the student/instructor role schema you infer. This couses the grader to crash on permission checks.

Grader-Service:
```
    File "/usr/local/lib/python3.8/dist-packages/grader_service/handlers/base_handler.py", line 319, in <dictcomp>
      for code, role in [tuple(g.split(":", 1)) for g in user["groups"]]
```

Lab-Extension: Grader-service not reachable, Error: 500

**Steps to reproduce the behavior**
1. login with a user which has groups assigned without colons (`:`) as seperators
2. start a notebook server with the lab-extension installed
3. wait till the service crashes

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Version 102.0.5005.115 (Official Build) (arm64)

**Additional context**

I guess this is already fixed in the main branch here: [https://github.com/TU-Wien-dataLAB/Grader-Service/blob/main/grader_service/grader_service/handlers/base_handler.py#L314](https://github.com/TU-Wien-dataLAB/Grader-Service/blob/main/grader_service/grader_service/handlers/base_handler.py#L314)

**Comment by meffmadd** [comment]
Thanks! Yes, this issue has been fixed but has not made it to a release yet.
