### ISSUE TITLE
Grader-config for individual assigments

### ISSUE THREAD

**Issue by joseftaha** [TU-Wien-dataLAB/Grader-Service#109]
#### :bulb: **Problem Statement**
Currently, the system doesn't allow instructors to customize their assignments on an individual basis. For example, instructors may want to include specific "TODO" code snippets to their assignments. 

#### :dart: **Proposed Solution**
I suggest introducing a new file named `grader-config.py` in each assignment's repository. This configuration file can hold user-defined configurations via Traitlets. These custom settings would override the default configurations in the `grader_convert` classes.

#### :books: **Additional Context**
This would greatly increase the flexibility of `grader_convert`. Instructors could customize functionalities specific to their courses or individual assignments. For instance, there's a preprocessor called `ClearSolutionPreprocessor` that performs important tasks like clearing the solution cells and inserting default code snippets. It has a Traitlet attribute `code_stub`, which could be customized via `grader-config.py` to insert different code snippets during assignment creation.

#### :hammer_and_wrench: **Implementation Plan**
- [x] **Add `-e` Flag to `grader_convert`**
    - **What**: Implement an optional `-e` flag to specify the path to `grader-config.py`.
    - **Why**: To enable custom configuration for the conversion and grading of assignments/submissions.

- [x] **Sanitize the configuration overrides**
   - **Why**: To prevent instructors from overriding all class traitlets.
 
- [x]  **Create Default `grader-config.py`**
    - **What**: Craft a default `grader-config.py` with all possible overridable Traitlet attributes, but leave values commented out.
    - **Why**: To provide a template for instructors, helping them understand what can be customized.

- [x]  **Update Grader Service**
    - **What**: Modify the grader service to recognize and utilize the new `-e` flag.
    - **Why**: To ensure the custom configuration is used when specified.

- [x] **Testing**

**Edited**: Updated the issue for clarity. Feedback and additional suggestions are most welcome!

**Comment by meffmadd** [comment]
What is the use case of this? We can already pass arbitrary config values to the labextension through the `jupyter_server_config.py`. So I'm not sure what advantages we get from using another config file. Is this meant for `grader_convert`?

**Comment by joseftaha** [comment]
Yes, the config file should enhance the flexibility of `grader_convert`. The idea is to let instructors tailor its functionalities according to their needs. They can do this by including a `grader-config.py` file that contains customized values for various "traitlets" attributes. These custom values will override the default settings of the `grader_convert` classes.

E.g: there's a preprocessor called [`clearsolution-preprocessor`](https://github.com/TU-Wien-dataLAB/Grader-Service/blob/main/grader_convert/grader_convert/preprocessors/clearsolutions.py) that performs two key tasks: it clears the content of solution cells and inserts a default code snippet in their place. This preprocessor has a traitlet attribute named `code_stub`, which dictates what this default code snippet should be. If an instructor wishes to use a different code snippet instead of the default one, they can specify their preferred snippet by setting the `code_stub` attribute in their `grader-config.py` file. This will then change the code snippet that gets inserted into the solution cells during the assignment creation process.

**Comment by adammccartney** [comment]
@joseftaha sounds good - just out of curiosity, have you thought about how the integration testing for this feature might work? Do you feel like there is an existing system that can model the production environment in a close enough way, or do we need to set one up or improve existing?

**Comment by adammccartney** [comment]
> @adammccartney, I am currently focused on "component testing" by directly evaluating the grader_convert command. To do this, I've manually created a test assignment repository and executed the grader_convert command on that repository. This allows me to test various use-cases and configurations. I am specifically looking to verify if grader_convert behaves as expected, especially when different settings are applied via a custom config file.

Okay, sounds good - are these ephemeral tests or will they be added to the test suite for `grader_convert`? Is there a lot of component logic that needs to be tested?

> 
> Following the component testing, I plan to perform integration and acceptance tests. These tests will evaluate the entire grading process through the user interface. To ensure the most accurate results, I agree that the development environment should closely mirror the production environment. In this case, I'm referring to the JaaS20 hub, that should be the same system as the production or do i get something wrong?

Great, the sooner we can get some feedback from integration tests the better. I believe that in our current setup, we have a single `hub` that runs in its own namespace. This is basically our production environment. Due to the way the architecture changed as part of the recent migration and the push to release the "single instance jupyterhub", it's a little bit more work to isolate some of the system components in a test instance. 

Previously `jaas20` had been deployed in its own namespace, along with it's own `hub` and `grader_service`. In the new architecture, the `jaas20` notebook is spawned as the user requests it at runtime and runs in the same "production" namespace, where it shares the `hub` and `grader_service` components with all other instances.

Do your changes affect `grader_service` or will they be isolated in user notebooks?
