### ISSUE TITLE
Can not create multiple assignments

### ISSUE THREAD

**Issue by florian-jaeger** [TU-Wien-dataLAB/Grader-Service#144]
**Describe the bug**
After creating an assignment, instructors can not create another assignment. When clicking on the create button nothing happens. (no request is sent as well)
It looks like the assignment creation form is not correctly initalised the second time around.
Only after closing the course management window and reopening it the assignment creation works again.

**Comment by meffmadd** [comment]
Closed by PR https://github.com/TU-Wien-dataLAB/Grader-Service/pull/154
