### ISSUE TITLE
Use browser storage to permanently set UI config

### ISSUE THREAD

**Issue by florian-jaeger** [TU-Wien-dataLAB/Grader-Service#147]
**Is your feature request related to a problem? Please describe.**
As a instructor I do not want to set all/latest/best submissions everytime I load the page. I also do not want to set the pagination each time.
**Describe the solution you'd like**
Use browser storage to permanently set UI config.

**Comment by meffmadd** [comment]
Implemented in cd23244e601143a9b20a45c56d3ddf27fb9fe558
