### ISSUE TITLE
UI Improvements Details grader_labextension release 0.3.0

### ISSUE THREAD

**Issue by mpetojevic** [TU-Wien-dataLAB/Grader-Service#155]
### UI Details - grader_labextension release 0.3.0

To improve the user experience in grader_labextension release 0.3.0, we want to implement the following details:

- [x] In the edit view of a submission, we want to add a log button, which then opens a modal, or card displaying logs.
- [x] Disable the Feedback generation button for submissions that aren't auto-graded. Please refer to issue #130 .
- [x] Allow instructors to set deadlines in the past, but when they do so, a short notification should be displayed stating that they are choosing a date in the past (maybe they did it unintentionally).
- [x] Instructors already have unlimited submissions, even if they've set a submission limit for their students. If they have submitted more times than they are allowed to, the submission count goes into negative numbers. Add a small chip next to the submission counter, indicating that, as instructors, they have an unlimited number of submissions. Number of submissions left should be updated right away (no need to reload page). (limit submissions to at least 0)
- [x] In the Detailed Submission View, the buttons (Pull Submission, Finish Manual Grading, Edit Submission) appear to be less user-friendly and self-explanatory, and it's not clear in which order the steps can or should be taken.  A slight redesign of this portion is wanted.
- [x] In the deadline extension view for students, we have no singular for 'Days' if the extension is for 1 *Day*.
- [x] Handle directories in file view better. Instead of showing the paths we should show parse them and maybe show a tree like structure or at lease split them and use > or other icons.

**Update**
Currently File Tree for FilesList looks like this and is fully functional:

![image](https://github.com/TU-Wien-dataLAB/Grader-Service/assets/130979144/41d2e780-8857-4790-a0f0-a7917875b8d4)

One thing that I would consider changing: Space between file icon and file name in the file list is much bigger than the space between folder icon and folder name. I discovered that it's because I added arrow icons for expanding/collapsing contents of the folder. These two icons take much more space than only the file icon.  ListItemText has the same indentation for both folder and file name which are hierarchically the same, but this much of a difference in blank space might not be wanted. Only setting margins for the file name isn't helpful here. ListItemText and ListItemIcon currenty have the same settings for file and folder case.

- [x] Find a way to handle the described situation to make FilesList look a bit better.
- [x] Fix "Missing File" and "Extra File" functionality with new file tree view (missing files should use the relative path whereas the current implementation uses just the name)

**Update**
Problems described above solved:

![image](https://github.com/TU-Wien-dataLAB/Grader-Service/assets/130979144/4ee0e0b7-e975-4312-ac21-8a6aed1c1eb5)

- [x] Add a message (similar to tooltip) besides the edit lecture "cog" icon for course manage view that tells instructors to give the lecture a human readable name if the lecture name is equal to the lecture code.
- [x] Feedback view for students is not scrollble
- [x] In create submission view, every time a student is selected an unnamed folder is created -> we thought this problem was solved, but it's not (we create directories in each of folders given to _makeDirs_ function):

```python
makeDirs(`${lectureBasePath}${lecture.code}`, [`create`, `${assignment.id}`, userDir])
```

**Comment by meffmadd** [comment]
I also need to update the extra files feature in the student file list. If the instructor checks the "Allow file upload by students" checkbox, the behavior should be disabled. I will work on this branch as well.

**Comment by meffmadd** [comment]
I also had to fix a bug in the student file view (warnings) which required changes in the `grader_service`. We therefor also have to make a release of `grader_service` when releasing these changes!

**Comment by meffmadd** [comment]
Before we release we should also investigate #162
