### ISSUE TITLE
Cannot delete released assignments and error message is not helpful

### ISSUE THREAD

**Issue by lumbric** [TU-Wien-dataLAB/Grader-Service#175]
**Describe the bug**
When trying to delete a released assignment, there is an error message saying: "Conflict".

**To Reproduce**
1. Create a new assignment
2. Open it -> Overview -> Release it
3. Go back to the overview of assignments
4. Click on :x: in the column "Delete Assignment"
5. Confirm deletion.
6. You will see the error message "Conflict" and the assignment is not deleted.

**Expected behavior**

One of the following two:
- Allow deleting released assignments
- A better error message: "Deleting released assignments is not allowed, first undo the release to delete the assignment.".

**Screenshots**
![image](https://github.com/TU-Wien-dataLAB/Grader-Service/assets/691772/f0672645-1b20-4d6c-8097-80a0dd0bb6f0)

**Comment by meffmadd** [comment]
Hi @lumbric! Thanks for writing the issue! We disabled the delete button when the assignment is released or complete and added a tooltip.
