### ISSUE TITLE
New cell does not show widgets in creation mode

### ISSUE THREAD

**Issue by meffmadd** [TU-Wien-dataLAB/Grader-Service#22]
**Describe the bug**
When adding a new cell to the notebook in creation mode, the new cell does not show the creation mode widget.

**To Reproduce**
1. Create new assignment, add notebook and enter creation mode
2. Add cell in any way (button, shortcut etc.)
3. Cell does not show any creation mode widgets (toggle needed)

**Expected behavior**
The widgets should be displayed automatically when new cell is added.

**Comment by florian-jaeger** [comment]
fixed
