### ISSUE TITLE
If a user deletes their latest submission, the latest submissions list query is incorrect

### ISSUE THREAD

**Issue by meffmadd** [TU-Wien-dataLAB/grader-service#243]
**Describe the bug**
In the "latest submissions" view, some users are missing if their latest submission for the assignment has been marked as deleted. This occurs because the query calculating each user's latest submission date does not filter out deleted submissions, leading the main query to join on a non-existent date if the latest submission was deleted.

https://github.com/TU-Wien-dataLAB/grader-service/blob/6f8be109077645c4c17bd6b68c0831da133f1511/grader_service/handlers/submissions.py#L105-L123

The `Submission.deleted == DeleteState.active` condition has to be added to the subquery as well. Also, we need to investigate where similar bugs might occur.

**Comment by florian-jaeger** [comment]
the lti endpoint in submission.py should have the same problem.
