### ISSUE TITLE
User score overview

### ISSUE THREAD

**Issue by florian-jaeger** [TU-Wien-dataLAB/Grader-Service#4]
**Is your feature request related to a problem? Please describe.**
As a student, I want to see my current scores of all my assignments.

**Describe the solution you'd like**
New view in the assignment tab which shows scores

**Comment by meffmadd** [comment]
Since students should not have access to the assignment properties to calculate the maximum possible scores of an assignment, we should create a new column in the assignment table for the max scores and update it on each assignment property PUT similar to how we do it for the submission scores.

**Comment by meffmadd** [comment]
I implemented the scores as an item in the assignment card and as secondary text in the submission list. Closing this issue for now.
