### ISSUE TITLE
Late Submission Penalty

### ISSUE THREAD

**Issue by florian-jaeger** [TU-Wien-dataLAB/Grader-Service#70]
## Initial Intentions / Goals

I would like to have a soft where students can get point deductions if they submit after the soft deadline.  
Currently we have a "hard deadline" configuration option and this remains the default for all assignment submissions. 
The proposed feature would augment the existing functionality.

The main goal of the feature is to make it possible to award a reduced amount of points for submissions that arrive for a certain time period after the hard deadline.

## Use Cases

Professors want to be generous and give students every possible opportunity to submit and assignment solution. Students want to party and don't always have the time to keep up with all of their professors boring demands.

Our primary concern from the user professors perspective:

+ The instructor will need to specify the scale of the penalties, specifically the number of periods that should be applied and the size of the penalty.

From the students perspective:
+ It should be clear from viewing the assignment what type of deadline is being applied, how much they stand to lose by submitting later, if a late submission is even allowed.

### Hard Deadline

Hard deadline is set by the instructor before they release an assignment. It represents the latest possible time that an assignment can be submitted. After the hard deadline has passed, no further submissions are allowed.

### Soft Deadline

If a soft deadline option is selected, we would like the ability to specify an array of tuples where the cost of the penalty is specified. The array would take the form:
```
[(P1,S1), ..., (PN,SN)]
```
Where `P` is the period where the scaling factor `S` is applied.

Importantly, this list would only make sense in the context of the tuple:

```
(T, [(P1,S1), ..., (PN, SN)])
```
Where `T` is the timestamp of the deadline. If no `(period, scale)` tuple is specified, i.e. if the array is empty, `(T, [])`, the deadline specified by the timestamp `T` is taken to be a hard deadline for the assignment.

This would then be used in some sort of control block to that applies the deduction upon the submission of a user assignment:

```
# subtract points on late submission according to scale 
scale = 0.0
if sub_ts < TS:
    scale = 1.0
else:
    for P, S in ??? 
        if sub_ts < TS + P:
            scale = S
    if scale == 0.0
        \# not accept
```

## Requirements
 
+ Provide a radio buttom for specifying whether a deadline?
+ if `soft deadline` is selected, provide a form for specifying the late submission penalty?
 
#### Instructor View 
+ A button in `Assignment/Settings` to enable the option of `Late Submission Penalty`. 
   **Note:** Total Points * Scaling Factor = Penalty.

+ A form in `Assignment/Settings` to configure the parameters of the `Late Submission Penalty`, specifically this form should make it possible to add `period`, `scaling factor` pairs that will be used to determine the grade of the submission.

#### Student View 

+ In `Assignment/Table` it should be clear if it is possible to submit after the deadline on condition of penalty
+ `Assignment/Detail View` - should clearly show the maximum possible points that are available during each submission period.

### Models
??? needs to be clarified

**Comment by adammccartney** [comment]
see `grader_labextension/handlers/submissions.py` for implementation details
