### ISSUE TITLE
Individual Assignments/Exams per Student based on username

### ISSUE THREAD

**Issue by websi96** [TU-Wien-dataLAB/Grader-Service#9]
**Is your feature request related to a problem? Please describe.**
In order to distribute exams to students, WU Vienna would need a way to hand-out individual instructions per student, to mitigate cheating.

**Describe the solution you'd like**
An automated way of distributing individual exams to students based on their username.

**Describe alternatives you've considered**
Currently the exams get synct to their home directories, there a named mapping is possible.

**Comment by websi96** [comment]
I think #3 is the same, right?

**Comment by florian-jaeger** [comment]
Yep
