### ISSUE TITLE
Using React Router for navigation in labextension

### ISSUE THREAD

**Issue by meffmadd** [TU-Wien-dataLAB/Grader-Service#92]
**Is your feature request related to a problem? Please describe.**
Navigation with modals and pop-ups is slow and troublesome for users.

**Describe the solution you'd like**
Navigation is handled by React Router which renders the paths in an outlet with breadcrumbs for global navigation.

**Overview of the tasks at hand**
- All components will be changed to work with the new router
 
***Components to be changed/updated***
- CourseManageComponent
- LectureListComponent

****Big changes**** 
Change to dataloading model for the larger components, these will now use the ReactRouter format, the smaller internal components will continue to pass props.

**Comment by adammccartney** [comment]
@meffmadd FYI, I just updated the branch pointer associated with the issue, I merged last weeks changes into "[migration/grader-labextension/upgrade-to-jupyterlab-4](https://github.com/TU-Wien-dataLAB/Grader-Service/commits/migration/grader-labextension/upgrade-to-jupyterlab-4)" and started a new branch: [feature/react-router-for-dataloading-components](https://github.com/TU-Wien-dataLAB/Grader-Service/tree/feature/react-router-for-dataloading-components) to handle the rest of the TODOs

**Comment by adammccartney** [comment]
Marking this as closed, further changes have been picked up in [feature/react-router-for-dataloading-components](https://github.com/TU-Wien-dataLAB/Grader-Service/tree/feature/react-router-for-dataloading-components)
