### ISSUE TITLE
Dynamic image selection for KubeGrader

### ISSUE THREAD

**Issue by florian-jaeger** [TU-Wien-dataLAB/Grader-Service#94]
**Is your feature request related to a problem? Please describe.**
As a instructor I want to configure the grading environment, when using the KubeGrader.

**Comment by meffmadd** [comment]
This could already be accomplished by the `default_image_name` traitlet. Users can already define a function that receives a lecture and an assignment that imports e.g. `requests` to load arbitrary data. 

However, the function should propably be renamed as the name suggests static values and more importantly should to be async to simplify data loading for users.

**Comment by meffmadd** [comment]
I have implemented the proposed changes. Please let me know if there is anything else to consider. In my opinion, the suggested solution offers the highest flexibility for defining custom dynamic solutions. As we previously discussed, the most likely solution involves making a REST call to an external service that resolves the image name. The current implementation is more than sufficient for this purpose.

**Comment by florian-jaeger** [comment]
Looks good!
